# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'viper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for viper
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'LightRoute', :git => 'https://github.com/SpectralDragon/LightRoute.git'

  target 'viperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'viperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
